In [1]:
print("Welcome to the world of machine learning")

Welcome to the world of machine learning


In [1]:
import numpy as np


In [3]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
arr3=np.zeros((3,4))
arr3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
arr4=np.identity(5)
arr4

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
arr5=np.arange(10)
arr5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr6=np.arange(2,10,2)
arr6

array([2, 4, 6, 8])

In [14]:
arr7=np.linspace(10,20,5)
arr7

array([10. , 12.5, 15. , 17.5, 20. ])

In [16]:
arr8=arr7.copy()
arr8

array([10. , 12.5, 15. , 17.5, 20. ])